# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  apisa-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: apisa-mysql
    volumes:
      - apisa-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=apisa
      - MYSQL_DATABASE=apisa
      - MYSQL_USER=apisa
      - MYSQL_PASSWORD=apisa

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.1-caddy
    container_name: apisa-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql